# Generated by Django 3.2.9 on 2021-11-27 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='is_ready',
            field=models.BooleanField(default=False),
        ),
    ]
