# Generated by Django 3.2.9 on 2021-11-28 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blogpost_is_ready'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='summary',
            field=models.TextField(),
        ),
    ]
